###Register
POST http://localhost:5000/api/user/register
Content-Type: application/json

{
    "name": "admin ne",
    "username":"admin",
    "password":"111qqqqq"
}

###Login
POST http://localhost:5000/api/user/login
Content-Type: application/json

{
    "username":"admin",
    "password":"111qqqqq"
}

###GetInfor
GET http://localhost:5000/api/user/infor
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGFkYjM0NjhlZjVmN2ZmYmVmMzAzNSIsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlIjoxLCJpYXQiOjE2NzkxNTM1NzgsImV4cCI6MTY3OTE2MDc3OH0.7xGmM-_CSZqGB6qy6YgwTkQtmvKtDeNVsPprqisO_mY"
Content-Type: application/json
#Bear Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0MGFkNGEyZDQwZDAwNGFjMzIxZmI3ZCIsInVzZXJuYW1lIjoid2lidXNhbWEiLCJyb2xlIjoxLCJpYXQiOjE2Nzg0MzEzOTQsImV4cCI6MTY3ODQzODU5NH0.b7FmgFQOyauT4KJaKMZi2eMnSAooLJgdbw_9v82xvnw
